### ISSUE TITLE
Import Trakt user list

### ISSUE THREAD

**Issue by hbooo** [pbrink231/plex_top_playlists#26]
Hi, 

I'm trying to import a playlist from trakt but as there is no example in the sample config I guess I'm doing it the wrong way, here is my config : 

```
trakt-movie-list: [
  { "title": "Movies Top Weekly", "type":"watched", "limit": 80, "url":"https://trakt.tv/users/donxy/lists/marvel-cinematic-universe?sort=rank,asc"}
  ]`
```

But when I try to import I have this error : 
`Bad Trakt Code`

I also tried
```
trakt-movie-list: [
  { "title": "Movies Top Weekly", "type":"watched", "limit": 80, 
  ] `
```
but I got
```
Movies Top Weekly: STARTING PLAYLIST - TYPE: watched - URL: https://api.trakt.tv/users/donxy/lists/marvel-cinematic-universe/items/type - KIND: playlist
Movies Top Weekly: WARNING - Playlist is empty
```

Got Bad Trakt Code too if I try with https://api.trakt.tv/users/donxy/lists/marvel-cinematic-universe/items/movie

It works fine with your samples in the config example

**Comment by pbrink231** [comment]
I dont think I ever tried a user list.

Only weekly and popular.  Will check this out this weekend.  Will probably have to make a new type to pull the right information.

**Comment by pbrink231** [comment]
Took a stab at this but realized I have set this to keep lists separated by movie or show.  I have realized playlist and collections can mix items.

This new user list you can get the items with
`https://api.trakt.tv/users/donxy/lists/marvel-cinematic-universe/items`

And it uses the same json scheme as watched.

The problem right now is since you can have mix movies and shows I need to do a rewrite.  This would be for the best but I dont have the time now.  I will try and tackle this in a week or two because I do not have time but any help is welcome.

**Comment by pbrink231** [comment]
So looking into this.

Trakt has list types of:
movie
episode
season
show

Plex Playlists have:
movie
episode

Plex Collections have:
movie
show

So my questions are:
For a trakt season and show, What is the best way to put those into a playlist.
possibilities:
- grab the last or first episode in the season/show and put only that one into the playlist (what I do now for trakt popular watched lists)
- grab all episodes in the season/show and add them in order to the playlist

For a collection it is rolled up so easier.
- If multiple episodes/seasons of a show are in a list then I ignore them and just add the show once.

**Comment by snickers2k** [comment]
i personally think plex-playlists are more or less dead. no improvments in any kind for years. the "share-playlists between users" request is 5 years old and got 800+ votes.

collections are far more advanced (has filters, batch-editing etc), besides the manual/curated order - plus it gives the oppurtunity to add/edit a few items from inside plex (for all users).

I personally use collections for all my "playlists" from now on and just name them with a dot up front.

**Comment by pbrink231** [comment]
Ok.  For a collection what I will do:
- If a season/episode is in the collection it will just be placed as a show
- If that show already exists in the synced list then I will ignore it and keep the position of the first item

For a playlist:
- If a show/season is in the collection I will grab the last available episode in the show
- If a show is repeated I will ignore it keeping the position the first time the show appeared

**Comment by mraniki** [comment]
@pbrink231  Is there an update on the support for custom list for tv or movie ?

**Comment by eltonzz** [comment]
@pbrink231 , many thanks for this awesome script.
Any updates on getting a custom Trakt playlist of episodes?

**Comment by pbrink231** [comment]
New update will finally get closer to fixing this.  Also the collections addition made to the plexapi library will allow for collections on shows now

**Comment by pbrink231** [comment]
To try out trakt user lists you need to be on the develop branch `git branch develop`.  I need to do some more testing before I push it on to master.  let me know if you find anything.

**Comment by pbrink231** [comment]
Develop branch has been merged into master.  This should now be working with trakt user lists
