### ISSUE TITLE
Are Collections are automatically updated after content changed?

### ISSUE THREAD

**Issue by Dex321x** [pbrink231/plex_top_playlists#32]
e.g.: a movie gets removed from imdb top 250, will it be automatically removed from the collection (tag removed) or does this only work with playlists?

Thanks!

**Comment by pbrink231** [comment]
For playlists they do get removed because I clear the playlist before adding the full new list.

For Collections.  I do not remove any collection tags.  So they will stay in that collection going forward.

Adding a call on collections to clear old items so I will clear old items if wanted.  I did not want to clear collections in case that tag was used already on other items.

**Comment by Dex321x** [comment]
Thanks for your explanation! So the lists are the way to go for me. Thanks for the excellent work!
