### ISSUE TITLE
Show missing TV Shows/Movies?

### ISSUE THREAD

**Issue by Fudge** [pbrink231/plex_top_playlists#7]
It would be great if I could see what I'm missing, especially on the IMDB top 250 playlist.

**Comment by pbrink231** [comment]
That shouldn't be too hard.

I am thinking a list of skipped after it creates the playlist so it will be blocked out nicely.  Do you think it would be better to dump it all at the end?

**Comment by spuniun** [comment]
I was going to create another issue but I realized this enhancement would suffice to resolve my particular issue. My Plex library is very large and very old so it seems I still have lots of movie entries whose metadata predates the "Plex Movie Scanner" option and are still using the legacy TMDb scanner metadata. This resulted in my lists missing a number of titles that should otherwise be found.
I confirmed that manually rematching them with the newer scanner and rerunning the script resolves the issue. So either this feature will let me identify all my titles that are missing (I have at least 225 of the Top 250 but only matched 60) or the addition of TMDb as you mention in the README will resolve it.

In any event, this script is a great little piece of work, I appreciate it a lot.

**Comment by pbrink231** [comment]
spuniun, I added a new issue according to what you said.  It is #8. I saw code before in JohnnyWang scripts so that should be an easy change.

I am figuring out how to keep the list together and do a loop to check a value of in a diction in another dictionary.  Once I have that both of these will be an easy add.

**Comment by pbrink231** [comment]
This now spits out the imdb_ids that are missing in a playlist if you set the ```show-missing-ids: True``` in the settings.ini file.
